# 服务
server:
  port: 9002

# 应用
spring:
  # 配置文件
  profiles:
    active: ${env:local}
  # 应用名称
  application:
    name: stud-online-api
  # 模板引擎
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/site/dist/
    suffix: .html
  # mvc框架
  mvc:
    static-path-pattern: /*
  # 资源路径
  resources:
    static-locations: classpath:/site/dist/,classpath:/templates/

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:profile/mybatis/mybatis-config.xml